// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdpygzrqeefylxdckcsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcHlnenJxZWVmeWx4ZGNrY3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODA3MjQsImV4cCI6MjA1MzY1NjcyNH0.5e_oVbV9UWd6kSR8iOWxkzxFEeQHSvLwxdne_gsqwaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);